apiVersion: v1
kind: Template
metadata:
  name: genexus-prod
objects:
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: genexus-prod